# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaeac41104b9ae17754751f97a6c8b52e662f881a161a99060de3ee95301a238de43db7c29e872661d373abe061e075c50463267c2879e8b7166d62b19f50b75

test:
  secret_key_base: 0f80395f2dc7e2741fb83f6242ec06c425166241aeae5a80e3b78ae99cf6b5db76fc3cda2b98e92d45f39108516c54ccd96e4396f3e659d8e88c47b1cf7aaa37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
